fix utf8 handeling in test name
pherkin/test-bdd-cucumber-perl pull request #191
Opened 2021-06-15 08:49 UTC by DragosTrif

This related to this bug https://stackoverflow.com/questions/67971552/testbddcucumberharnesshtml-breaks-utf-8-characters
BR, Dragos Trif

2021-07-17 14:59 UTC, Grinnz commented on t/test_utf8_test_name.t
> +	is(1, 1, $text );
This test looks wrong. This text contains bytes, not characters.

2021-07-17 15:01 UTC, Grinnz commented
Test2 handles encoding internally. Thus test descriptions are expected to be characters. Perl does not have "utf8 strings" and it's best to stop thinking of it that way. Perl strings are sequences of codepoints, which may represent either Unicode characters or bytes. You want them in the Unicode character form when using them in text operations.

2021-07-17 15:32 UTC, DragosTrif commented
@Grinnz the test is wrong but the problem still because it ignores  App::pherkin::_pre_run which dose this  binmode STDOUT, ':utf8'; and doubles encodes the test output. But the problem is still there any suggestions to address this  would be much appreciated

2021-07-17 15:35 UTC, Grinnz commented
binmode on STDOUT will break Test2 in general, probably.

2021-07-17 17:47 UTC, ehuelsmann commented
Actually, the comments added to the tests *inside* the feature execution (as: `ok(1, 'comment');`) , won't get routed through STDOUT on the `pherkin` app: output from "feature" execution is captured and handed to the formatter for handling.

In your gist which you referenced in the chat channel (https://gist.github.com/DragosTrif/017b64b9855c74a944d6a7308ebdbf08), you gave:

```perl
Given qr/^input of (.*)$/,
    sub {
      S->{'data'} = $1;
       my $path = Mojo::File->new('test.json');
      my $text = $path->slurp;
      
      $text = Encode::decode('UTF-8', $text);
      my $h = $coder->decode($text);
      my $json = $coder->encode($h);
      # ran with pherkin -o Html nesting/ > test.html
      # this prints cootectly in the html file
      print $json;
      # this dose not print utf8 chars
      is(1,1,$json);
    };
```

It's not completely clear how `$coder` is instantiated, but if it's done the same way as in the test you submitted, it's a `Cpanel::JSON::XS`.

Going over the various strings in the above example in order to understand if they're bytes or characters, I get:

* `my $text = $path->slurp;`  
  `$text` holds bytes
* `my $text = Encode::decode('UTF-8'), $text)`  
  `$text` holds characters
* `my $h = $coder->decode($text)`  
  `decode` expects a string with characters (a "unicode string"), when created without the 'utf8' boolean set
* `my $json  = $coder->encode($h);  
  `$json` contains characters (aka a "unicode string")
* `print $json;`  
  prints the unicode string `$json` through "STDOUT" with ':utf8' binmode converting the characters to UTF-8 in the output stream
* `is(1, 1, $json);`
  provides the characters held in $json for processing to Test2's implementation of `is` (that's not in the sample above, but I assume this; is that correct?)

@Grinnz would you say the above understanding is correct?

2021-07-17 17:52 UTC, Grinnz commented
Yes, in that instance the decode step turns it into a character string, which would be appropriate for Test2's is().

2021-07-17 17:53 UTC, Grinnz commented
However, printing to STDOUT in tests is a bug. STDOUT is reserved for TAP, you must use diag or note (which also take characters in Test2).

2021-07-17 17:55 UTC, Grinnz commented
Oh, I think I understand your comment about STDOUT now. So this setup is routing the TAP aside from STDOUT.

2021-07-17 18:00 UTC, ehuelsmann commented
> Oh, I think I understand your comment about STDOUT now. So this setup is routing the TAP aside from STDOUT.

Yes. The output is captured in a scalar instead of sent to STDOUT and from that scalar routed to a formatter which might send it to STDOUT or anywhere else.

2021-07-17 18:26 UTC, ehuelsmann commented on t/test_utf8_test_name.t
> +like($result, qr/"Piteşti"/, "utf8 strings are ok in test name");
And the step succeeds, because this isn't UTF8 either! Now I understand what's going on!

2021-07-17 18:34 UTC, ehuelsmann commented
@DragosTrif I'm going to suggest a number of changes to  this PR; ideally, you make those, so I can merge your PR and the commits get correctly attributed to you in the history of this project. If you don't feel like doing that, no problem, let me know. I'll make them myself, I'm just not sure that gets the attribution right.

2021-07-17 18:37 UTC, DragosTrif commented
@ehuelsmann I will try to do implement your suggestion this weekend.

2021-07-17 18:41 UTC, ehuelsmann requested changes
We're almost there, now that @Grinnz helped me to understand the root cause.

2021-07-17 18:41 UTC, ehuelsmann commented on lib/Test/BDD/Cucumber/Executor.pm
> +use Encode qw( decode );
Could you remove the `qw( decode )` part? You're referencing the name of the function by its qualified name anyway and this reduces chances for collision.

2021-07-17 18:41 UTC, ehuelsmann commented on lib/Test/BDD/Cucumber/Executor.pm
> +            output => Encode::decode('utf8', $utf8_test_result),
Could you move this `decode` call to line 710 (the `return` statement in the `_test_output()` function); that function should transparently return a string instead of the accidental byte-stream it currently did.

2021-07-17 18:41 UTC, ehuelsmann commented on t/test_utf8_test_name.t
> +use warnings;
Please add `use utf8;` here, because this file depends on some of it being read as UTF8 text.

2021-07-17 18:41 UTC, ehuelsmann commented on t/test_utf8_test_name.t
> +	my $json = '{ "cc":"Piteşti" }';
When you add `use utf8;` above, I'm expecting you need to `use Encode` too and `$json = Encode::encode('UTF-8', $json);` here because the string will contain characters, but you want the string to contain bytes to make the roundtrip below work as intended.

2021-07-18 10:05 UTC, ehuelsmann commented on t/test_utf8_test_name.t
> +use Cpanel::JSON::XS;
One last nit: we don't need to use the JSON module anymore.

2021-07-18 10:24 UTC, ehuelsmann approved these changes

2021-07-18 10:25 UTC, merged

2021-07-18 11:09 UTC, ehuelsmann commented on t/test_utf8_test_name.t
> +use Test::BDD::Cucumber::Harness::Html;
Ah. The merge broke, because the HTML harness was still required, but I think that too isn't necessary. I'll push  an update.